Eve4SalesApp/Models/EditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eve4SalesApp.Models
{
    public class EditModel
    {

        public int CovTransId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }

        public string Market { get; set; }
        public int xMarket { get; set; }
        public int Year { get; set; }
        public int Sales { get; set; }
          public int Rank { get; set; }
        public bool DeleteModel { get; set; }

        public bool ManualAdd { get; set; }

        public bool RollOn { get; set; }

        public int RollOnYear { get; set; }
               
    }
}

Eve4SalesApp/Controllers/MaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eve4SalesApp.Models;
using System.Data.SqlClient;

namespace Eve4SalesApp.Controllers
{
    public class MaintenanceController : Controller
    {
        private SalesDb db = new SalesDb();

        // GET: Maintenance
        [Authorize]
        public ActionResult UpdateRelease()
        {

            ReleaseModel rm = db.CurrentRelease.First();

            if (rm == null)
            {
                return HttpNotFound();
            }

            return View(rm);

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateRelease([Bind(Include = "TransID,CurrentRelease")] ReleaseModel rm)
        {


            if (ModelState.IsValid)
            {
                db.Entry(rm).State = EntityState.Modified;
                db.SaveChanges();

            }
            return View("UpdateReleaseSuccess");

        }



        public ActionResult EditModel(int transId)
        {

                  
            SqlParameter xid = new SqlParameter("@TransId", transId);

            EditModel em = db.Database.SqlQuery<EditModel>("sp_UIEditModel_Select @TransId", xid).FirstOrDefault();

            if (em == null)
            {
                return HttpNotFound();
            }

            return View(em);

        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditModel([Bind(Include = "CovTransId,Make,Model,Market,xMarket,Year,Sales,DeleteModel,ManualAdd,RollOn,RollOnYear")] EditModel em)
        {


            if (ModelState.IsValid)
            {
                /* int trId = em.CovTransId; 
                 var xmarket = (from c in db.ModelYearDeclarations
                                   join m in db.SalesMarketModels on c.MarketModelId equals m.MarketModelId
                                   where c.TransID.Equals(trId)
                                  select m.MarketCode);
                 string xxmarket = xmarket.First().ToString(); */

                
                             
               

                if (em.RollOn) {

                    UserEditModel ue = new UserEditModel();

                    ue.Make = em.Make;
                    ue.Model = em.Model;
                    ue.Sales = 1;
                    ue.Rank = em.Rank;
                    ue.SalesYearBegin = em.RollOnYear;
                    ue.SalesYearEnd = em.RollOnYear;
                    ue.UnknownSales = true;
                    ue.MarketCode = new List<string> { em.Market };

                    foreach (string xMarket in ue.MarketCode)
                    {

                        for (int xYear = ue.SalesYearBegin; xYear <= ue.SalesYearEnd; xYear++)
                        {




                            SqlParameter make = new SqlParameter("@Make", ue.Make);
                            SqlParameter model = new SqlParameter("@Model", ue.Model);
                            SqlParameter sales = new SqlParameter("@Sales", ue.Sales);
                            SqlParameter salesyear = new SqlParameter("@SalesYear", xYear);
                            SqlParameter marketcode = new SqlParameter("@MarketCode", xMarket);
                            SqlParameter unknownsales = new SqlParameter("@UnknownSales", ue.UnknownSales);
                            SqlParameter rank = new SqlParameter("@Rank", ue.Rank);

                            db.Database.ExecuteSqlCommand("sp_UIAddNewMarketModelTransaction @Make, @Model, @Sales, @SalesYear, @MarketCode, @UnknownSales, @Rank",
                                               make, model, sales, salesyear, marketcode, unknownsales, rank);

                        }

                    }









                } else { 


                    SqlParameter xid = new SqlParameter("@TransId", em.CovTransId);
                    SqlParameter sales = new SqlParameter("@Sales", em.Sales);
                    SqlParameter deleteModel = new SqlParameter("@DeleteModel", em.DeleteModel);
        
                  
                    SqlParameter year = new SqlParameter("@SalesYear", em.Year);
                SqlParameter zmarket = new SqlParameter("@MarketCode", em.Market);

                db.Database.ExecuteSqlCommand("sp_UIEditModel_Update @TransId, @Sales, @DeleteModel",
                                       xid, sales, deleteModel);

                db.Database.ExecuteSqlCommand("sp_AssignTiering @MarketCode, @SalesYear",
                                      zmarket, year);

                }


                return View("EditModelSuccess");

               
              


            }
            else { 
            return View("EditModelError");

            }
        }







        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eve4SalesApp/Views/Maintenance/EditModel.cshtml
@model Eve4SalesApp.Models.EditModel

@{
    ViewBag.Title = "EditModel";
    int roOoption1 = Model.Year + 1;
    int roOoption2 = Model.Year + 2;
    int roOoption3 = Model.Year + 3;
}


<div class="container">
    <div style="margin-top:50px;" class="mainbox col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><h4>Model Options</h4></div>

            </div>
            <div style="padding-top:30px; padding-left: 100px;" class="panel-body">



                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.HiddenFor(model => model.CovTransId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CovTransId, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.xMarket, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.xMarket, "", new { @class = "text-danger" })


                            @Html.HiddenFor(model => model.ManualAdd, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ManualAdd, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.RollOn, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RollOnYear, "", new { @class = "text-danger" })


                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Market, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Market, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Market, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly"
                           } })
                                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Rank, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sales, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Sales, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sales, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                        

                        <div class="form-group">
                            <label class="control-label col-md-3">Delete model?
                                <a href="#" data-toggle="tooltip" title="Model will be deleted for the referenced market and year only"><span class="glyphicon glyphicon-info-sign"></span></a>
                            </label>
                            <div class="col-md-9">
                                <div class="checkbox-inline">

                                    <label class="checkbox-inline checkbox-bootstrap-na checkbox-lg">
                                        <input type="checkbox" id="DeleteModel" class="DeleteModel" name="DeleteModel" value="true" />

                                        <span class="checkbox-placeholder-na"></span>
                                    </label>

                                </div>
                            </div>
                        </div>


                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update Sales" id="submitForm" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }


            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index", "SalesModels")
</div>


                <script src="~/Scripts/jquery-1.10.2.js"></script>
                <script type="text/javascript">


                    $('#DeleteModel').change(function () {
                        if ($('#DeleteModel').is(':checked') == true) {
                            $('#Sales').prop('readonly', true);
                            $('#RollOn').prop('disabled', true);
                            $('#RollOnYear').prop('readonly', true);
                            $('#submitForm').val("Delete Model");
                            $('#submitForm').removeClass("btn btn-primary");
                            $('#submitForm').addClass("btn btn-danger");

                            console.log('checked');
                        }
                    });

                    $('#DeleteModel').change(function () {
                        if ($('#DeleteModel').is(':checked') == false) {
                            $('#Sales').prop('readonly', false);
                            $('#RollOn').prop('disabled', false);
                            $('#submitForm').val("Update Sales");
                            $('#submitForm').removeClass("btn btn-danger");
                            $('#submitForm').addClass("btn btn-primary");

                            console.log('checked');
                        }
                    });

          
                </script>

Eve4SalesApp/Views/Maintenance/EditModelError.cshtml
@{
    ViewBag.Title = "Error";
   
}

<br />
<div class="well">

    <h2><span class="glyphicon glyphicon-warning-sign"> </span> &nbsp; Ooops! Something went wrong</h2>
    <h3>Please check the data and try again</h3>
    <br />
    @Html.ActionLink("<< Back to list", "Index", "SalesModels")

</div>

Eve4SalesApp/Views/Maintenance/EditModelSuccess.cshtml
@model Eve4SalesApp.Models.ReleaseModel

@{
    ViewBag.Title = "Update Release";
}


<br />
<div class="well">

    <h2><span class="glyphicon glyphicon-saved"> </span> &nbsp; Changes Saved</h2>
    <br />
    @Html.ActionLink("<< Return to list", "Index", "SalesModels")

Eve4SalesApp/Views/Maintenance/UpdateRelease.cshtml
@model Eve4SalesApp.Models.ReleaseModel

@{
    ViewBag.Title = "Update Release";
}


<div class="container">
    <div style="margin-top:50px;" class="mainbox col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Update Current Release Global Parameter</div>

            </div>
            <div style="padding-top:30px; padding-left: 100px; background-color:#FFFFFF;" class="panel-body">

               

                @using (Html.BeginForm("UpdateRelease", "Maintenance", FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.AntiForgeryToken()
                    <div style="align-content:center">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.TransID)
                        @Html.EditorFor(model => model.CurrentRelease, new { htmlAttributes = new { @class = "form-control input-lg" } })
                        <input type="submit" value="Update" class="btn-lg btn-success" />
                        @Html.ValidationMessageFor(model => model.CurrentRelease, "", new { @class = "text-danger" })
                    </div>
                }

                <br />


            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back Home", "Index", "Home")
</div>

Eve4SalesApp/Views/Maintenance/UpdateReleaseSuccess.cshtml
@model Eve4SalesApp.Models.ReleaseModel

@{
    ViewBag.Title = "Update Release";
}


<br />
<div class="well">

    <h2><span class="glyphicon glyphicon-saved"> </span> &nbsp; Release parameter successfully saved. Happy Sourcing!</h2>
    <br />
    @Html.ActionLink("<< Return Home", "Index", "Home")