Eve4SalesApp/Models/ModelYearDeclaration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Eve4SalesApp.Models
{

    [Table("CoverageMaps")]
    public class ModelYearDeclaration
    {

        [Key]
        public int TransID { get; set; }
        public int MarketModelId { get; set; }
        public int ForYear { get; set; }
        public bool DoneFlag { get; set; }
        public bool NotAvailableFlag { get; set; }
        public string BacklogInfo { get; set; }           
        public string ReleaseInfo { get; set; }

    }
}

Eve4SalesApp/Controllers/ModelYearDeclarationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eve4SalesApp.Models;
using System.Activities.Expressions;
using System.Data.SqlClient;

namespace Eve4SalesApp.Controllers
{
    public class ModelYearDeclarationsController : Controller
    {
        private SalesDb db = new SalesDb();

     
        // GET: ModelYearDeclarations/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModelYearDeclaration modelYearDeclaration = db.ModelYearDeclarations.Find(id);
                       
                                   
            if (modelYearDeclaration == null)
            {
                return HttpNotFound();
            }
                        
            return PartialView("_UpdateCoveragePartial", modelYearDeclaration);

           
        }

        

        // POST: ModelYearDeclarations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TransID,MarketModelId,ForYear,DoneFlag,NotAvailableFlag,BacklogInfo,ReleaseInfo")] ModelYearDeclaration modelYearDeclaration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modelYearDeclaration).State = EntityState.Modified;
                db.SaveChanges();

                
                SqlParameter release = new SqlParameter("@release", modelYearDeclaration.ReleaseInfo);
                SqlParameter releaseNull = new SqlParameter("@release", "empty");
                SqlParameter transid = new SqlParameter("@TransId", modelYearDeclaration.TransID);
                SqlParameter doneflag = new SqlParameter("@done", modelYearDeclaration.DoneFlag);
                SqlParameter naflag = new SqlParameter("@na", modelYearDeclaration.NotAvailableFlag);
                SqlParameter user = new SqlParameter("@User", User.Identity.Name);


                if (String.IsNullOrEmpty(modelYearDeclaration.ReleaseInfo)) {

                    db.Database.ExecuteSqlCommand("sp_UICoverageUpdateAdmin @TransId, @done, @na, @release, @User",
                                                   transid, doneflag, naflag, releaseNull, user);

                } else {

                    db.Database.ExecuteSqlCommand("sp_UICoverageUpdateAdmin @TransId, @done, @na, @release, @User",
                                                 transid, doneflag, naflag, release, user);

                }
                               
                            }

            return RedirectToAction("Index", "SalesModels");
        }



     
                

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eve4SalesApp/Views/ModelYearDeclarations/Edit.cshtml
@model Eve4SalesApp.Models.ModelYearDeclaration

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Model/Year Coverage</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ModelYearDeclaration</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransID)

        <div class="form-group">
            @Html.LabelFor(model => model.SalesModelID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SalesModelID, new { @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ForYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ForYear, new { @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoneFlag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DoneFlag)
                    @Html.ValidationMessageFor(model => model.DoneFlag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

}

Eve4SalesApp/Views/ModelYearDeclarations/UpdateRelease.cshtml
@model Eve4SalesApp.Models.ReleaseModel

@{
    ViewBag.Title = "Update Release";
}

<h3>Update Release</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReleaseModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CurrentRelease)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Eve4SalesApp/Views/ModelYearDeclarations/_UpdateCoveragePartial.cshtml
@model Eve4SalesApp.Models.ModelYearDeclaration





                   <div class="modal-body">

                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">Update Model Coverage</h4> 
                       <br />
 

                    @using (Html.BeginForm("Edit", "ModelYearDeclarations"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-inline">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.TransID)

                            <div class="form-group">

                                <div class="hidden">
                                    @Html.HiddenFor(model => model.MarketModelId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MarketModelId, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.ForYear, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ForYear, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.ReleaseInfo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ReleaseInfo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <br />

                            <div class="form-group">
                                <div>
                                    <div class="checkbox-inline">

                                        <label class="checkbox-inline checkbox-bootstrap checkbox-lg">
                                            <input type="checkbox" class="checkbox" name="DoneFlag" value="true" />

                                            <span class="checkbox-placeholder"></span>
                                            Declare this model as <b>DONE</b>
                                        </label>

                                    </div>
                                </div>


                            </div>

                            <div class="form-group">
                                <div>
                                    <div class="checkbox-inline">

                                        <label class="checkbox-inline checkbox-bootstrap-na checkbox-lg">
                                            <input type="checkbox" class="checkbox" name="NotAvailableFlag" value="true" />

                                            <span class="checkbox-placeholder-na"></span>
                                            Model Not Available
                                        </label>

                                    </div>
                                </div>

                             </div>
                            <div class="form-group">
                                <div class="col-md-2">
                                    <input type="submit" value="Save" class="btn btn-primary" />
                                </div>
                            </div>

                            <br />                                                                                    
                            <hr />
                        </div>
                    }

                       <center> @Html.ActionLink("Model Options", "EditModel", "Maintenance", new { transId = Model.TransID}, new { @class = "btn-default btn" })</center>




                </div>