Eve4SalesApp/Models/SalesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eve4SalesApp.Models
{
    public class SalesModel
    {

        [Key]
        public int SalesModelID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string BacklogGrp { get; set; }
        public int? GrpOID { get; set; }
    }
}

Eve4SalesApp/Models/StatsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eve4SalesApp.Models
{
    public class StatsViewModel
    {

        [Key]
        public string Make { get; set; }
        public double gCalcValue { get; set; }
        public double yCalcValue { get; set; }
        public int ModelCount { get; set; }
        public int SalesYear { get; set; }
        public int SalesCount { get; set; }
        public double MarketShare { get; set; }
        public string MarketCode { get; set; }

    }
}

Eve4SalesApp/Controllers/SalesModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eve4SalesApp.Models;
using System.Data.SqlClient;

namespace Eve4SalesApp.Controllers
{
    public class SalesModelsController : Controller
    {
        private SalesDb db = new SalesDb();

        // GET: SalesModels
        public ActionResult Index(string marketCode = null, int timeFrame = 0, string refinedSearch = null)
        {
            
            if (marketCode == null) { marketCode = (string)TempData["mc"]; TempData["mc"] = marketCode; }
            else { TempData["mc"] = marketCode;  }

            if (timeFrame == 0) { timeFrame = (int)TempData["tf"]; TempData["tf"] = timeFrame; }
            else { TempData["tf"] = timeFrame; }

            if (refinedSearch == null) {

                            refinedSearch = (string)TempData["rs"]; TempData["rs"] = refinedSearch;

            } else if (refinedSearch == "."){

                            refinedSearch = "";
                            TempData["rs"] = refinedSearch;

            } else {

                            TempData["rs"] = refinedSearch;
            }

            ViewBag.CurrentMarketCode = marketCode;
            ViewBag.CurrentYear = timeFrame;
            ViewBag.refinedSearch = refinedSearch; 

         
       var model = from s in db.SalesModels
                        join m in db.SalesMarketModels on s.SalesModelID equals m.SalesModelId
                        join d in db.ModelYearDeclarations on m.MarketModelId equals d.MarketModelId
                        join f in db.SalesFigures on m.MarketModelId equals f.MarketModelId
                        join a in db.PortalStats on s.Make equals a.Make
                        where f.TimeFrame.Equals(timeFrame) && m.MarketCode.Contains(marketCode) && d.ForYear.Equals(timeFrame)
                   orderby s.SalesModelID ascending, d.ForYear ascending
                        select new MapViewModel
                        {
                            MarketModelId = m.MarketModelId,
                            Make = s.Make,
                            Model = s.Model,
                            Market = m.MarketCode,
                            TotalSales = f.TotalSales,
                            TransID = d.TransID, 
                            ForYear = d.ForYear,
                            DoneFlag = d.DoneFlag, 
                            NotAvailableFlag = d.NotAvailableFlag,
                            MakeColour = a.Colour, 
                            Tier = f.Tier, 
                            ModelRank = f.ModelRank,
                            BacklogGrp = s.BacklogGrp, 
                            GrpOID = s.GrpOID, 
                            ReleaseInfo = d.ReleaseInfo, 
                            ManualAdd = f.ManualAdd,
                            SalesCalculatedFromRank = f.SalesCalculatedFromRank
                        };

            if (refinedSearch != null) {

                model = model.Where( x => (x.Make.Contains(refinedSearch)) || (x.Model.Contains(refinedSearch)));
                
            }


            if (!String.IsNullOrEmpty(marketCode))
            {
                model = model.Where(s => s.Market.Contains(marketCode))
                             .OrderBy(s => s.ModelRank);

            }
            return View(model);



        }


        public ActionResult Stats()
        {
            
            var marketcodelist = (from mc in db.SalesMarketModels
                                  select mc.MarketCode).Distinct().ToList();

            ViewBag.ListofMarkets = marketcodelist;

            var yearlist = (from mc in db.SalesFigures
                            orderby mc.TimeFrame
                            select mc.TimeFrame).Distinct().ToList();

            ViewBag.ListofYears = yearlist;

            
            return View();
            
        }
         
         public ActionResult StatsResult(int timeframe = 2017, string marketcode = "NA")
        {


            var stats = db.Database.SqlQuery<StatsViewModel>("sp_CalculateMarketPercentage_Partial @SalesYear, @MarketCode",
    new SqlParameter("@SalesYear", timeframe),
    new SqlParameter("@MarketCode", marketcode));


            return View(stats); 


        }


        public ActionResult AggEu(int timeframe = 2018)
        {


            var list = db.Database.SqlQuery<AggEuList>("sp_CalculateEuAggSales @SalesYear",
    new SqlParameter("@SalesYear", timeframe));

            ViewBag.TimeFrame = timeframe;

            var yearlist = (from mc in db.SalesFigures
                            orderby mc.TimeFrame descending
                            select mc.TimeFrame).Distinct().ToList();

            ViewBag.ListofYears = yearlist;



            return View(list);


        }


        public ActionResult MarketOverview()
        {


            var overview = db.Database.SqlQuery<MarketOverviewViewModel>("sp_MarketPerCentageOverview"); 


            return View(overview);


        }
        
               

        // GET: SalesModels/Create
        [Authorize]
        public ActionResult Create()
        {
            var marketcodelist = (from mc in db.SalesMarketModels

           select mc.MarketCode).Distinct().ToList();

            ViewBag.ListofMarkets = marketcodelist;

            var makeList = (from mc in db.PortalStats
                            orderby mc.Make descending
                            select mc.Make).Distinct().ToList();

            ViewBag.ListOFMakes = makeList;

            var yearList = (from yl in db.SalesFigures
                            select yl.TimeFrame).Distinct().ToList();

            int maxYear = (from yl in db.SalesFigures
                            select yl.TimeFrame).Max();

            yearList.Add(maxYear + 1);
            yearList.Add(maxYear + 2);
            yearList.Add(maxYear + 3);

            ViewBag.ListOFYears = yearList;

            var rankList = (from yl in db.SalesFigures
                            select yl.ModelRank).Distinct().ToList();

            int maxRank = (from yl in db.SalesFigures
                           select yl.ModelRank).Max();


            rankList.Add(maxRank + 1);

            ViewBag.ListOfRanks = rankList;


            return View();
        }

        // POST: SalesModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Make,Model,Sales,SalesYearBegin,SalesYearEnd,MarketCode,UnknownSales,Rank")] UserEditModel ueModel)
        {

           if (ModelState.IsValid)
            {

                if (ueModel.SalesYearEnd < ueModel.SalesYearBegin)
                {

                    return View("CreateError");


                } else {

                    /*   try
                       { */



                           bool unknownsalesCheck = false;

                           if (ueModel.UnknownSales != null && ueModel.UnknownSales != false)
                           {

                               unknownsalesCheck = true;
                           }


                           int? rankCheck = 0;

                           if (ueModel.Rank == null)
                           {

                               rankCheck = 0;
                           }
                           else
                           {

                               rankCheck = ueModel.Rank;

                           }




                           foreach (string xMarket in ueModel.MarketCode)
                           {

                               for (int xYear = ueModel.SalesYearBegin; xYear <= ueModel.SalesYearEnd; xYear++)
                               {




                                   SqlParameter make = new SqlParameter("@Make", ueModel.Make);
                                   SqlParameter model = new SqlParameter("@Model", ueModel.Model);
                                   SqlParameter sales = new SqlParameter("@Sales", ueModel.Sales);
                                   SqlParameter salesyear = new SqlParameter("@SalesYear", xYear);
                                   SqlParameter marketcode = new SqlParameter("@MarketCode", xMarket);
                                   SqlParameter unknownsales = new SqlParameter("@UnknownSales", unknownsalesCheck);
                                   SqlParameter rank = new SqlParameter("@Rank", rankCheck);

                                   db.Database.ExecuteSqlCommand("sp_UIAddNewMarketModelTransaction @Make, @Model, @Sales, @SalesYear, @MarketCode, @UnknownSales, @Rank",
                                                      make, model, sales, salesyear, marketcode, unknownsales, rank);

                               }

                           }


                  /*     }
                       catch {

                           return View("CreateError");

                       } */


                    return View("CreateSummary");

                }
                               
            }
            else
            {

                return View("CreateError");

            }

          
            
        }

        // GET: SalesModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SalesModel salesModel = db.SalesModels.Find(id);
            if (salesModel == null)
            {
                return HttpNotFound();
            }
            return View(salesModel);
        }

        // POST: SalesModels/Edit/5

Eve4SalesApp/Views/SalesModels/AggEu.cshtml
@model IEnumerable<Eve4SalesApp.Models.AggEuList>

@{
    ViewBag.Title = "EU Aggregate Sales Data";
}

<h3>Showing EU Aggregate Sales Data (@ViewBag.TimeFrame)</h3>

<form method="get" class="form-inline">
  

    @Html.DropDownList("timeframe", new SelectList(ViewBag.ListofYears).OrderByDescending(x => x.Text), new { @class = "form-control" })

    <input type="submit" value="Submit" class="btn-primary btn" width="100" />
</form>

    <br /><br />

    <table class="table table-bordered" cellpadding="5" style="width:100%;">
        <tr tr style="background: #eeeeee;">
            <th>
                EU Rank
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                EU Aggregate Sales
            </th>
            <th>
                Associated Markets
            </th>
            <th>
                Coverage
            </th>


        </tr>

        @foreach (var item in Model)
        {
            if (item.Coverage)
            {
                
             @:   <tr style="background: rgba(0, 255, 0, 0.2);">
                }
            else
            {

                @:   <tr style="background: rgba(255, 0, 0, 0.2);">
    }

            <td>
                @Html.DisplayFor(modelItem => item.EURank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalEU)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarketList)
            </td>
            <td>
                @if (item.Coverage)
                {

                    <center> <span class="glyphicon glyphicon-ok"></span></center>

                }


            </td>



            @:  </tr>


        }

    </table>

Eve4SalesApp/Views/SalesModels/Create.cshtml
@model Eve4SalesApp.Models.UserEditModel

@{
    ViewBag.Title = "New Data";
}

<div class="container">
    <div style="margin-top:50px;" class="mainbox col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><h4>Add new sales data</h4></div>

            </div>
            <div style="padding-top:30px; padding-left: 100px;" class="panel-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4><b>NOTE:</b> Any duplicate transactions created will be merged - Sales figures will be updated</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3">Make</label>
                            <div class="col-md-9">

                                @Html.DropDownList("make", new SelectList(ViewBag.ListofMakes, "make").OrderBy(x => x.Text), "Select Make", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Model</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Markets
                                <a href="#" data-toggle="tooltip" title="NOTE: Select multiple markets by holding down the CTRL key"><span class="glyphicon glyphicon-info-sign"></span></a>
                            </label>

                            <div class="col-md-6">
                              
                                    @Html.ListBoxFor(model => model.MarketCode, new MultiSelectList(ViewBag.ListofMarkets), new { @class = "form-control", @style = "height:100px"})
                                    @Html.ValidationMessageFor(model => model.MarketCode, "", new { @class = "text-danger" })
</div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Year Begin</label>
                            <div class="col-md-6">
                                @Html.DropDownList("SalesYearBegin", new SelectList(ViewBag.ListofYears, "SalesYearBegin").OrderBy(x => x.Text), "Select Start Year", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SalesYearBegin, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Year End</label>
                            <div class="col-md-6">
                                @Html.DropDownList("SalesYearEnd", new SelectList(ViewBag.ListofYears, "SalesYearEnd").OrderBy(x => x.Text), "Select End Year", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SalesYearEnd, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="control-label col-md-3">No. Of Sales</label>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Sales, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sales, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Sales Figures Not Available</label>
                            <div class="col-md-6">
                                <div class="checkbox-inline">

                                    <label class="checkbox-inline checkbox-bootstrap-na checkbox-lg">
                                        <input type="checkbox" id="UnknownSales" class="UnknownSales" name="UnknownSales" value="true" />

                                        <span class="checkbox-placeholder-na"></span>
                                    </label>

                                </div>
                                </div>
                            </div>

               

                        <div class="form-group">
                            <label class="control-label col-md-3">Desired Rank
                                <a href="#" data-toggle="tooltip" title="Arbitrary Sales Figures will be assigned to all manually ranked models. NOTE: If the selected rank number exceeds the lowest ranked vehicle, the next available rank will be assigned"><span class="glyphicon glyphicon-info-sign"></span></a>
                            </label> 
                            <div class="col-md-6">
                                @Html.DropDownList("Rank", new SelectList(ViewBag.ListofRanks, "Rank").OrderBy(x => x.Text.AsInt()), "Select Rank", new { @class = "form-control", @disabled = "disabled" })
                                @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9">
                               
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-3">
                                <input type="submit" value="+ Add" class="btn-lg btn-info" />
                            </div>
                        </div>


                    </div>
                }
            </div>
            </div>
        </div>
    </div>

            <div>
                @Html.ActionLink("Return Home", "Index", "Home")
            </div>


<script src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">


    $('#UnknownSales').change(function () {
        if ($('#UnknownSales').is(':checked') == true) {
            $('#Sales').val('-1').prop('disabled', true);
            $('#Rank').prop('disabled', false);

            console.log('checked');
        } else {
            $('#Sales').val('').prop('disabled', false);
            $('#Rank').prop('disabled', true);

            console.log('unchecked');
        }
    });



</script>

Eve4SalesApp/Views/SalesModels/CreateError.cshtml
@{
    ViewBag.Title = "Error";
   
}

<br />
<div class="well">

    <h2><span class="glyphicon glyphicon-warning-sign"> </span> &nbsp; Ooops! Something went wrong</h2>
    <h3>Please check the data and try again</h3>
    <br />
    @Html.ActionLink("<< Try Again", "Create", "SalesModels")

</div>

Eve4SalesApp/Views/SalesModels/CreateSummary.cshtml
@{
    ViewBag.Title = "Data Added";
   
}

<br />
<div class="well">

<h2><span class="glyphicon glyphicon-saved"> </span> &nbsp; Sales data successfully added</h2>
<h3>New models should now appear in models list</h3>
<br />
    @Html.ActionLink("<< Add more models", "Create", "SalesModels")

</div>

Eve4SalesApp/Views/SalesModels/Index.cshtml
@model IEnumerable<Eve4SalesApp.Models.MapViewModel>

@{
    ViewBag.Title = "Track Coverage";
}



<div id='myModal' class='modal fade'>
    <div class="modal-dialog" >
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>

</div>   

<div class="container">
    <div class="col-sm-10">
        <h3>Showing data for @ViewBag.CurrentMarketCode/@ViewBag.CurrentYear</h3>
        <form method="get" class="form-inline">
            <input type="search" name="refinedSearch" class="form-control" value="@ViewBag.refinedSearch" />
            <input type="submit" value="Filter" class="btn btn-primary" />
            @if (@ViewBag.refinedSearch != "" && @ViewBag.refinedSearch != null )
            {
            @Html.ActionLink("Reset", "Index", "SalesModels", new { timeframe = ViewBag.CurrentYear, marketcode = ViewBag.CurrentMarketCode, refinedSearch = "." }, new { @class = "btn btn-info" })
            }

         </form>

    <br />
    </div>
    <div class="col-md-2">
        <br /><br />

        @Html.ActionLink("Show Stats", "StatsResult", "SalesModels", new { timeframe = ViewBag.CurrentYear, marketcode = ViewBag.CurrentMarketCode }, new { @class = "btn-info btn" })

</div>

    </div>

<table class="table table" cellpadding="5" width:100%">
    <tr style="background: #eeeeee;">
        <th>
            Rank/Tier
        </th>
        <th>
            Make 
        </th>
        <th>
            Model
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Market)
        </th>
         <th>
           Total Sales (@ViewBag.CurrentYear)
        </th>
       <th>Release</th>

@if (User.Identity.IsAuthenticated)
{
    <th>
        @if (ViewBag.CurrentMarketCode != "NA"){
        <center> Click To Update &nbsp; <a href="#" data-toggle="tooltip" title="Updating coverage will update all EU markets"><span class="glyphicon glyphicon-warning-sign"></span></a></center>
        } else {
        <center>Click To Update </center>
            }
</th>
}
else
{
    <th>
        <center> Coverage &nbsp; <a href="#" data-toggle="tooltip" title="Log-in to update coverage"><span class="glyphicon-lock"></span></a></center>
    </th>


}

</tr>
  
     @foreach (var item in Model)
     {


         if (item.DoneFlag)
         {
           @: <tr style="background: rgba(0, 255, 0, 0.2);">
                } else { 
           @: <tr style="background: rgba(255, 0, 0, 0.2);">
           }

                <td>#@item.ModelRank (T-@item.Tier)</td>

                <td>
                   <font style="color: @item.MakeColour.Trim();"> @Html.DisplayFor(modelItem => item.Make) </font>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Market)
                </td>

                <td> @if (item.TotalSales < 0)
                {

                        <b>TBD</b>

                }
                else
                {

                    if (item.ManualAdd == true && !(item.SalesCalculatedFromRank == true))
                    {    @item.TotalSales @:&nbsp; 
                        <a href="#" data-toggle="tooltip" title="Manual Add" style="color: #000000"><span class="glyphicon glyphicon-exclamation-sign"></span></a> }
                    else if (item.ManualAdd == true && item.SalesCalculatedFromRank == true)
                    {
                       <i><font style="color:darkgray;"> @item.TotalSales</font></i> @:&nbsp;
                        <a href="#" data-toggle="tooltip" title="Manual Add - Sales Figures calculatation based on Rank" style="color: #000000"><span class="glyphicon glyphicon-exclamation-sign"></span></a> }

                    else {
                    @item.TotalSales
                    }
                }

    </td>

    <td>@item.ReleaseInfo</td>
           
            <td>

                @if (User.Identity.IsAuthenticated)
                {

                    @Html.HiddenFor(modelItem => item.TransID)
                    @Html.HiddenFor(modelItem => item.ForYear)


                    if (item.DoneFlag && !(item.NotAvailableFlag))
                    {

                        <center> <a href="javascript:void(0);" class="CoverageEdit" title="Click to update coverage" data-id="@item.TransID"><img src="@Url.Content("~/Content/circle_tick.png")" width="20" height="20"></a> </center>

                    }
                    else if (!(item.DoneFlag) && !(item.NotAvailableFlag))
                    {

                        <center><a href="javascript:void(0);" class="CoverageEdit" title="Click to update coverage" data-id="@item.TransID"><img src="@Url.Content("~/Content/circle.png")" width="20" height="20"></a></center>

                    }

                    else
                    {

                        <center> <a href="javascript:void(0);" class="CoverageEdit" title="Click to update coverage" data-id="@item.TransID"><img src="@Url.Content("~/Content/redx.png")" width="20" height="20"></a> </center>

                    }

                }
                else
                {
                    
                    if (item.DoneFlag && !(item.NotAvailableFlag))
                    {

                        <center><img src="@Url.Content("~/Content/circle_tick.png")" width="20" height="20"></center>

                    }
                    else if (!(item.DoneFlag) && !(item.NotAvailableFlag))
                    {

                        <center><img src="@Url.Content("~/Content/circle.png")" width="20" height="20"></center>

                    }

                    else
                    {
                        <center> <img src="@Url.Content("~/Content/redx.png")" width="20" height="20"></center>

                    }

                }
            </td>


         @:   </tr>       
}        




 </table>
 

Eve4SalesApp/Views/SalesModels/MarketOverview.cshtml
@model IEnumerable<Eve4SalesApp.Models.MarketOverviewViewModel>

@{
    ViewBag.Title = "Markets Overview";
}

<br />
<h4>Market Overview by Year</h4>

<br />

<table class="table-striped" width="100%" cellpadding="20" style="font-size:12px;">
    <tr>
        <td align="right">
           <b>Sales Year </b>
        </td>

        <td align="right">
            <b>North America </b>
</td>
        <td align="right">
            <b>Germany </b>
        </td>
        <td align="right">
            <b>France</b>
        </td>
        <td align="right">
            <b>UK</b>
        </td>
        <td align="right">
            <b>Italy</b>
        </td>
        </tr>

@foreach (var item in Model) {
    <tr>

        <td align="right">
            <b>@Html.DisplayFor(modelItem => item.SalesYear) </b>
        </td>

        <td align="right">
            @Html.DisplayFor(modelItem => item.naVal)%
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.deVal)%
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.frVal)%
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.ukVal)%
        </td>
        <td align="right">
            @Html.DisplayFor(modelItem => item.itVal)%
        </td>
       
    </tr>
}

</table>

Eve4SalesApp/Views/SalesModels/Stats.cshtml
@{
    ViewBag.Title = "Stats";
}


<div class="container">

    <div style="padding:30px;">
       
        @using (Html.BeginForm("StatsResult", "SalesModels", FormMethod.Get, new { @class = "form-horizontal" }))
        {

            @Html.DropDownList("marketCode", new SelectList(ViewBag.ListofMarkets, "marketCode"), "Select Market", new { @class = "form-control" })



            @Html.DropDownList("timeFrame", new SelectList(ViewBag.ListofYears, "timeFrame"), "Select Timeframe", new { @class = "form-control" })


            <input type="submit" value="Go!" class="btn btn-default" width="100" />

        }
        </div>

    </div>

Eve4SalesApp/Views/SalesModels/StatsResult.cshtml
@model IEnumerable<Eve4SalesApp.Models.StatsViewModel>

@{
    ViewBag.Title = "Statistics";
}

<br />
@Html.ActionLink("<< Back to list", "Index", "SalesModels", null, new { @class = "btn-default btn" })
<br /><br />


@foreach (var item in Model)
{
    if (item.Make.Trim() == "A")
    {

      @:  <div class="panel panel-body" style="background: #EEEEEE; border: 1px solid black; ">
            <div class="col-sm-3">
                <span><h2>@item.MarketCode</h2></span>
                <span><h3>@item.SalesYear</h3></span>
                <div class="col-sm-3"></div>

            </div>
            <br /><br />
            <div class="col-sm-4" style="align-content: center;" >
                <div id="pink" data-percent="@item.gCalcValue" class="big">
            </div>
   
            </div>


    }
    else if (item.Make.Trim() == "X")
    {

        
        <div class="col-sm-2" align="center">
                <br /><br /> <br />
                <div id="green" data-percent="@item.gCalcValue" class="small" style="align-content:center">
                 
                </div>
        </div>

            <div class="col-sm-3" align="center">

                
                <br /><br /> <br />
                <div id="yellow" data-percent="@item.yCalcValue" class="small">
                    </div>

            </div>
           
            




      @:  </div>


    @: <div class="panel panel-body" style="background: #EEEEEE; border: 1px solid black; ">




    } else if (item.Make.Trim() == "T1") {
double width = item.gCalcValue;
<label>T1 (@item.gCalcValue%)</label>
<div id="tier1" data-width="@width" data-background="#BFEDEF"></div>
<br />

    }
    else if (item.Make.Trim() == "T2")
    {
        double width = item.gCalcValue;
 <label>T2 (@item.gCalcValue%)</label>
<div id="tier2" data-width="@width" data-background="#BBC7CE"></div>
<br />

    }
    else if (item.Make.Trim() == "T3")
    {
        double width = item.gCalcValue;
<label>T3 (@item.gCalcValue%)</label>
<div id="tier3" data-width="@width" data-background="#C4B7CB"></div>

@:</div>

<h4>Top Makes - @item.MarketCode / @item.SalesYear </h4>
@: <table class="table-striped table-bordered table-hover" style="width:100%; position:center;" cellpadding="10">

    <tr>
        <th>Make</th>
        <th>% of Car Park</th>
        <td align="right"><b>Coverage</b></td>
        </tr>



    } else
    {


    <tr style="font-size: medium;">
        <td>@item.Make</td>
        <td>@item.MarketShare%</td>
        <td align="right"><b>@item.gCalcValue%</b></td>
      

    </tr>

    }

    }

</table>